title : Jeremy Walworth
tagline: Ruby on Rails developer for Verizon Biz. Maker, hacker, brewer, vintner, father, sinner, aviator, shaolin kempo karate practitioner
author :
  name : Jeremy Walworth
  email : walworth@gmail.com
  github : jeremyfsu
  twitter : username
  feedburner : feedname

navigation :
  - about.md
  - archive.html
  - zen.md
